# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_gps_importer.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_BatchGpsImporter(object):
    def setupUi(self, BatchGpsImporter):
        BatchGpsImporter.setObjectName(_fromUtf8("BatchGpsImporter"))
        BatchGpsImporter.setEnabled(True)
        BatchGpsImporter.resize(711, 408)
        self.horizontalLayout = QtGui.QHBoxLayout(BatchGpsImporter)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tab_widget = QtGui.QTabWidget(BatchGpsImporter)
        self.tab_widget.setMinimumSize(QtCore.QSize(680, 0))
        self.tab_widget.setObjectName(_fromUtf8("tab_widget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setVerticalSpacing(29)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(self.tab)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.input_gpx_folder = QtGui.QLineEdit(self.tab)
        self.input_gpx_folder.setObjectName(_fromUtf8("input_gpx_folder"))
        self.gridLayout.addWidget(self.input_gpx_folder, 0, 1, 1, 2)
        self.label_3 = QtGui.QLabel(self.tab)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.input_gpx_file_btn = QtGui.QPushButton(self.tab)
        self.input_gpx_file_btn.setObjectName(_fromUtf8("input_gpx_file_btn"))
        self.gridLayout.addWidget(self.input_gpx_file_btn, 0, 3, 1, 1)
        self.input_projection_cbo = QgsProjectionSelectionWidget(self.tab)
        self.input_projection_cbo.setMaximumSize(QtCore.QSize(16777215, 23))
        self.input_projection_cbo.setObjectName(_fromUtf8("input_projection_cbo"))
        self.gridLayout.addWidget(self.input_projection_cbo, 3, 1, 1, 3)
        self.scan_sub_folders_rdb = QtGui.QRadioButton(self.tab)
        self.scan_sub_folders_rdb.setChecked(True)
        self.scan_sub_folders_rdb.setObjectName(_fromUtf8("scan_sub_folders_rdb"))
        self.gridLayout.addWidget(self.scan_sub_folders_rdb, 1, 1, 1, 1)
        self.input_format_auto_chk = QtGui.QCheckBox(self.tab)
        self.input_format_auto_chk.setObjectName(_fromUtf8("input_format_auto_chk"))
        self.gridLayout.addWidget(self.input_format_auto_chk, 2, 3, 1, 1)
        self.label_6 = QtGui.QLabel(self.tab)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 3, 0, 1, 1)
        self.input_format_cbo = QtGui.QComboBox(self.tab)
        self.input_format_cbo.setObjectName(_fromUtf8("input_format_cbo"))
        self.gridLayout.addWidget(self.input_format_cbo, 2, 1, 1, 2)
        self.no_scan_sub_folders_rbtn = QtGui.QRadioButton(self.tab)
        self.no_scan_sub_folders_rbtn.setObjectName(_fromUtf8("no_scan_sub_folders_rbtn"))
        self.gridLayout.addWidget(self.no_scan_sub_folders_rbtn, 1, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label_11 = QtGui.QLabel(self.tab)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 4, 0, 1, 1)
        self.geometry_type_cbo = QtGui.QComboBox(self.tab)
        self.geometry_type_cbo.setObjectName(_fromUtf8("geometry_type_cbo"))
        self.gridLayout.addWidget(self.geometry_type_cbo, 4, 1, 1, 3)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.tab_widget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.output_shp_file = QtGui.QLineEdit(self.tab_2)
        self.output_shp_file.setObjectName(_fromUtf8("output_shp_file"))
        self.gridLayout_2.addWidget(self.output_shp_file, 3, 1, 1, 2)
        self.label_4 = QtGui.QLabel(self.tab_2)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        self.lineEdit = QtGui.QLineEdit(self.tab_2)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.gridLayout_2.addWidget(self.lineEdit, 2, 1, 1, 2)
        self.output_shp_file_btn = QtGui.QPushButton(self.tab_2)
        self.output_shp_file_btn.setObjectName(_fromUtf8("output_shp_file_btn"))
        self.gridLayout_2.addWidget(self.output_shp_file_btn, 3, 3, 1, 1)
        self.label_5 = QtGui.QLabel(self.tab_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.exclude_with_errors_rbtn = QtGui.QRadioButton(self.tab_2)
        self.exclude_with_errors_rbtn.setObjectName(_fromUtf8("exclude_with_errors_rbtn"))
        self.gridLayout_2.addWidget(self.exclude_with_errors_rbtn, 1, 1, 1, 1)
        self.extent_box = QgsExtentGroupBox(self.tab_2)
        self.extent_box.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.extent_box.setFlat(False)
        self.extent_box.setCheckable(True)
        self.extent_box.setChecked(False)
        self.extent_box.setCollapsed(False)
        self.extent_box.setSyncGroup(_fromUtf8(""))
        self.extent_box.setScrollOnExpand(False)
        self.extent_box.setSaveCollapsedState(False)
        self.extent_box.setSaveCheckedState(False)
        self.extent_box.setObjectName(_fromUtf8("extent_box"))
        self.gridLayout_2.addWidget(self.extent_box, 0, 1, 1, 3)
        self.no_exclude_with_errors_rbtn = QtGui.QRadioButton(self.tab_2)
        self.no_exclude_with_errors_rbtn.setObjectName(_fromUtf8("no_exclude_with_errors_rbtn"))
        self.gridLayout_2.addWidget(self.no_exclude_with_errors_rbtn, 1, 2, 1, 1)
        self.label_7 = QtGui.QLabel(self.tab_2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 2, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.tab_2)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_2.addWidget(self.label_10, 3, 0, 1, 1)
        self.pushButton = QtGui.QPushButton(self.tab_2)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout_2.addWidget(self.pushButton, 2, 3, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_2)
        self.tab_widget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.tab_4)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.scrollArea = QtGui.QScrollArea(self.tab_4)
        self.scrollArea.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 652, 298))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.progress_text_edit = QtGui.QTextEdit(self.scrollAreaWidgetContents)
        self.progress_text_edit.setFrameShape(QtGui.QFrame.Box)
        self.progress_text_edit.setFrameShadow(QtGui.QFrame.Sunken)
        self.progress_text_edit.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.progress_text_edit.setObjectName(_fromUtf8("progress_text_edit"))
        self.verticalLayout_5.addWidget(self.progress_text_edit)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_6.addWidget(self.scrollArea)
        self.tab_widget.addTab(self.tab_4, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tab_widget)
        self.buttonBox = QtGui.QDialogButtonBox(BatchGpsImporter)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Help|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.dynamic_help_box = QtWebKit.QWebView(BatchGpsImporter)
        self.dynamic_help_box.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dynamic_help_box.sizePolicy().hasHeightForWidth())
        self.dynamic_help_box.setSizePolicy(sizePolicy)
        self.dynamic_help_box.setUrl(QtCore.QUrl(_fromUtf8("about:blank")))
        self.dynamic_help_box.setRenderHints(QtGui.QPainter.HighQualityAntialiasing|QtGui.QPainter.SmoothPixmapTransform|QtGui.QPainter.TextAntialiasing)
        self.dynamic_help_box.setObjectName(_fromUtf8("dynamic_help_box"))
        self.horizontalLayout.addWidget(self.dynamic_help_box)

        self.retranslateUi(BatchGpsImporter)
        self.tab_widget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), BatchGpsImporter.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), BatchGpsImporter.reject)
        QtCore.QMetaObject.connectSlotsByName(BatchGpsImporter)

    def retranslateUi(self, BatchGpsImporter):
        BatchGpsImporter.setWindowTitle(_translate("BatchGpsImporter", "Batch GPS Importer", None))
        self.label.setText(_translate("BatchGpsImporter", "GPX folder", None))
        self.label_3.setText(_translate("BatchGpsImporter", "Scan sub-folders", None))
        self.input_gpx_file_btn.setText(_translate("BatchGpsImporter", "Browse...", None))
        self.scan_sub_folders_rdb.setText(_translate("BatchGpsImporter", "Yes", None))
        self.input_format_auto_chk.setText(_translate("BatchGpsImporter", "Auto detect", None))
        self.label_6.setText(_translate("BatchGpsImporter", "GPX projection", None))
        self.no_scan_sub_folders_rbtn.setText(_translate("BatchGpsImporter", "No", None))
        self.label_2.setText(_translate("BatchGpsImporter", "GPX Format", None))
        self.label_11.setText(_translate("BatchGpsImporter", "Geometry type", None))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab), _translate("BatchGpsImporter", "Input and Output", None))
        self.label_4.setText(_translate("BatchGpsImporter", "Exclude with geometry error", None))
        self.output_shp_file_btn.setText(_translate("BatchGpsImporter", "Browse...", None))
        self.label_5.setText(_translate("BatchGpsImporter", "Restrict extent", None))
        self.exclude_with_errors_rbtn.setText(_translate("BatchGpsImporter", "Yes", None))
        self.no_exclude_with_errors_rbtn.setText(_translate("BatchGpsImporter", "No", None))
        self.label_7.setText(_translate("BatchGpsImporter", "Included folder", None))
        self.label_10.setText(_translate("BatchGpsImporter", "Excluded folder", None))
        self.pushButton.setText(_translate("BatchGpsImporter", "Browse...", None))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab_2), _translate("BatchGpsImporter", "Validation", None))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab_4), _translate("BatchGpsImporter", "Progress", None))

from PyQt4 import QtWebKit
from qgis.gui import QgsExtentGroupBox, QgsProjectionSelectionWidget
