# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gps_importer.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_BatchGpsImporter(object):
    def setupUi(self, BatchGpsImporter):
        BatchGpsImporter.setObjectName(_fromUtf8("BatchGpsImporter"))
        BatchGpsImporter.setEnabled(True)
        BatchGpsImporter.resize(587, 424)
        self.horizontalLayout = QtGui.QHBoxLayout(BatchGpsImporter)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tab_widget = QtGui.QTabWidget(BatchGpsImporter)
        self.tab_widget.setMinimumSize(QtCore.QSize(556, 0))
        self.tab_widget.setObjectName(_fromUtf8("tab_widget"))
        self.input_output_tab = QtGui.QWidget()
        self.input_output_tab.setObjectName(_fromUtf8("input_output_tab"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.input_output_tab)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setVerticalSpacing(29)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.no_scan_sub_folders_rbtn = QtGui.QRadioButton(self.input_output_tab)
        self.no_scan_sub_folders_rbtn.setObjectName(_fromUtf8("no_scan_sub_folders_rbtn"))
        self.gridLayout.addWidget(self.no_scan_sub_folders_rbtn, 1, 2, 1, 1)
        self.label_6 = QtGui.QLabel(self.input_output_tab)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 1)
        self.geometry_type_cbo = QtGui.QComboBox(self.input_output_tab)
        self.geometry_type_cbo.setObjectName(_fromUtf8("geometry_type_cbo"))
        self.gridLayout.addWidget(self.geometry_type_cbo, 4, 1, 1, 3)
        self.route = QtGui.QCheckBox(self.input_output_tab)
        self.route.setChecked(True)
        self.route.setObjectName(_fromUtf8("route"))
        self.gridLayout.addWidget(self.route, 2, 3, 1, 1)
        self.input_gpx_file_btn = QtGui.QPushButton(self.input_output_tab)
        self.input_gpx_file_btn.setObjectName(_fromUtf8("input_gpx_file_btn"))
        self.gridLayout.addWidget(self.input_gpx_file_btn, 0, 3, 1, 1)
        self.label = QtGui.QLabel(self.input_output_tab)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_11 = QtGui.QLabel(self.input_output_tab)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 4, 0, 1, 1)
        self.scan_sub_folders_rdb = QtGui.QRadioButton(self.input_output_tab)
        self.scan_sub_folders_rdb.setChecked(True)
        self.scan_sub_folders_rdb.setObjectName(_fromUtf8("scan_sub_folders_rdb"))
        self.gridLayout.addWidget(self.scan_sub_folders_rdb, 1, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.input_output_tab)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.input_gpx_folder = QtGui.QLineEdit(self.input_output_tab)
        self.input_gpx_folder.setObjectName(_fromUtf8("input_gpx_folder"))
        self.gridLayout.addWidget(self.input_gpx_folder, 0, 1, 1, 2)
        self.input_projection_cbo = QgsProjectionSelectionWidget(self.input_output_tab)
        self.input_projection_cbo.setMaximumSize(QtCore.QSize(16777215, 23))
        self.input_projection_cbo.setObjectName(_fromUtf8("input_projection_cbo"))
        self.gridLayout.addWidget(self.input_projection_cbo, 5, 1, 1, 3)
        self.track = QtGui.QCheckBox(self.input_output_tab)
        self.track.setChecked(True)
        self.track.setObjectName(_fromUtf8("track"))
        self.gridLayout.addWidget(self.track, 2, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.input_output_tab)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.waypoint = QtGui.QCheckBox(self.input_output_tab)
        self.waypoint.setChecked(True)
        self.waypoint.setObjectName(_fromUtf8("waypoint"))
        self.gridLayout.addWidget(self.waypoint, 2, 2, 1, 1)
        self.layer_name_edit = QtGui.QLineEdit(self.input_output_tab)
        self.layer_name_edit.setMaxLength(50)
        self.layer_name_edit.setObjectName(_fromUtf8("layer_name_edit"))
        self.gridLayout.addWidget(self.layer_name_edit, 3, 1, 1, 3)
        self.label_8 = QtGui.QLabel(self.input_output_tab)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 3, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.tab_widget.addTab(self.input_output_tab, _fromUtf8(""))
        self.validation_tab = QtGui.QWidget()
        self.validation_tab.setObjectName(_fromUtf8("validation_tab"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.validation_tab)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.invalid_gpx_folder = QtGui.QLineEdit(self.validation_tab)
        self.invalid_gpx_folder.setObjectName(_fromUtf8("invalid_gpx_folder"))
        self.gridLayout_2.addWidget(self.invalid_gpx_folder, 6, 1, 1, 2)
        self.label_5 = QtGui.QLabel(self.validation_tab)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 4, 0, 1, 1)
        self.invalid_folder_btn = QtGui.QPushButton(self.validation_tab)
        self.invalid_folder_btn.setObjectName(_fromUtf8("invalid_folder_btn"))
        self.gridLayout_2.addWidget(self.invalid_folder_btn, 6, 3, 1, 1)
        self.valid_folder_btn = QtGui.QPushButton(self.validation_tab)
        self.valid_folder_btn.setObjectName(_fromUtf8("valid_folder_btn"))
        self.gridLayout_2.addWidget(self.valid_folder_btn, 5, 3, 1, 1)
        self.label_10 = QtGui.QLabel(self.validation_tab)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_2.addWidget(self.label_10, 6, 0, 1, 1)
        self.exclude_with_few_points = QtGui.QRadioButton(self.validation_tab)
        self.exclude_with_few_points.setObjectName(_fromUtf8("exclude_with_few_points"))
        self.buttonGroup_2 = QtGui.QButtonGroup(BatchGpsImporter)
        self.buttonGroup_2.setObjectName(_fromUtf8("buttonGroup_2"))
        self.buttonGroup_2.addButton(self.exclude_with_few_points)
        self.gridLayout_2.addWidget(self.exclude_with_few_points, 4, 1, 1, 1)
        self.no_exclude_few_points = QtGui.QRadioButton(self.validation_tab)
        self.no_exclude_few_points.setObjectName(_fromUtf8("no_exclude_few_points"))
        self.buttonGroup_2.addButton(self.no_exclude_few_points)
        self.gridLayout_2.addWidget(self.no_exclude_few_points, 4, 2, 1, 1)
        self.no_exclude_with_errors_rbtn = QtGui.QRadioButton(self.validation_tab)
        self.no_exclude_with_errors_rbtn.setObjectName(_fromUtf8("no_exclude_with_errors_rbtn"))
        self.buttonGroup = QtGui.QButtonGroup(BatchGpsImporter)
        self.buttonGroup.setObjectName(_fromUtf8("buttonGroup"))
        self.buttonGroup.addButton(self.no_exclude_with_errors_rbtn)
        self.gridLayout_2.addWidget(self.no_exclude_with_errors_rbtn, 3, 2, 1, 1)
        self.exclude_with_errors_rbtn = QtGui.QRadioButton(self.validation_tab)
        self.exclude_with_errors_rbtn.setObjectName(_fromUtf8("exclude_with_errors_rbtn"))
        self.buttonGroup.addButton(self.exclude_with_errors_rbtn)
        self.gridLayout_2.addWidget(self.exclude_with_errors_rbtn, 3, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.validation_tab)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 3, 0, 1, 1)
        self.valid_gpx_folder = QtGui.QLineEdit(self.validation_tab)
        self.valid_gpx_folder.setObjectName(_fromUtf8("valid_gpx_folder"))
        self.gridLayout_2.addWidget(self.valid_gpx_folder, 5, 1, 1, 2)
        self.label_7 = QtGui.QLabel(self.validation_tab)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 5, 0, 1, 1)
        self.extent_box = QgsExtentGroupBox(self.validation_tab)
        self.extent_box.setMaximumSize(QtCore.QSize(16777215, 150))
        self.extent_box.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.extent_box.setFlat(False)
        self.extent_box.setCheckable(True)
        self.extent_box.setChecked(False)
        self.extent_box.setProperty("collapsed", False)
        self.extent_box.setProperty("syncGroup", _fromUtf8(""))
        self.extent_box.setProperty("scrollOnExpand", False)
        self.extent_box.setProperty("saveCollapsedState", False)
        self.extent_box.setProperty("saveCheckedState", False)
        self.extent_box.setObjectName(_fromUtf8("extent_box"))
        self.gridLayout_2.addWidget(self.extent_box, 2, 1, 1, 3)
        self.label_9 = QtGui.QLabel(self.validation_tab)
        self.label_9.setWordWrap(True)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_2.addWidget(self.label_9, 2, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_2)
        self.tab_widget.addTab(self.validation_tab, _fromUtf8(""))
        self.fields_tab = QtGui.QWidget()
        self.fields_tab.setObjectName(_fromUtf8("fields_tab"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.fields_tab)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_12 = QtGui.QLabel(self.fields_tab)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_3.addWidget(self.label_12, 0, 0, 1, 1)
        self.exclude_fields_groupbox = QtGui.QGroupBox(self.fields_tab)
        self.exclude_fields_groupbox.setCheckable(True)
        self.exclude_fields_groupbox.setObjectName(_fromUtf8("exclude_fields_groupbox"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.exclude_fields_groupbox)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.exclude_fields_view = QtGui.QTreeView(self.exclude_fields_groupbox)
        self.exclude_fields_view.setFrameShape(QtGui.QFrame.Box)
        self.exclude_fields_view.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.exclude_fields_view.setAlternatingRowColors(False)
        self.exclude_fields_view.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.exclude_fields_view.setObjectName(_fromUtf8("exclude_fields_view"))
        self.horizontalLayout_2.addWidget(self.exclude_fields_view)
        self.gridLayout_3.addWidget(self.exclude_fields_groupbox, 0, 1, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_3)
        spacerItem = QtGui.QSpacerItem(24, 200, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.tab_widget.addTab(self.fields_tab, _fromUtf8(""))
        self.log_tab = QtGui.QWidget()
        self.log_tab.setObjectName(_fromUtf8("log_tab"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.log_tab)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.scrollArea = QtGui.QScrollArea(self.log_tab)
        self.scrollArea.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 528, 314))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.progress_text_edit = QtGui.QTextEdit(self.scrollAreaWidgetContents)
        self.progress_text_edit.setFrameShape(QtGui.QFrame.Box)
        self.progress_text_edit.setFrameShadow(QtGui.QFrame.Sunken)
        self.progress_text_edit.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.progress_text_edit.setObjectName(_fromUtf8("progress_text_edit"))
        self.verticalLayout_5.addWidget(self.progress_text_edit)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_6.addWidget(self.scrollArea)
        self.tab_widget.addTab(self.log_tab, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.about_box = QtGui.QTextEdit(self.tab)
        self.about_box.setFrameShape(QtGui.QFrame.Box)
        self.about_box.setObjectName(_fromUtf8("about_box"))
        self.verticalLayout_7.addWidget(self.about_box)
        self.tab_widget.addTab(self.tab, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tab_widget)
        self.buttonBox = QtGui.QDialogButtonBox(BatchGpsImporter)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Help|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.dynamic_help_box = QtWebKit.QWebView(BatchGpsImporter)
        self.dynamic_help_box.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dynamic_help_box.sizePolicy().hasHeightForWidth())
        self.dynamic_help_box.setSizePolicy(sizePolicy)
        self.dynamic_help_box.setUrl(QtCore.QUrl(_fromUtf8("about:blank")))
        self.dynamic_help_box.setRenderHints(QtGui.QPainter.HighQualityAntialiasing|QtGui.QPainter.SmoothPixmapTransform|QtGui.QPainter.TextAntialiasing)
        self.dynamic_help_box.setObjectName(_fromUtf8("dynamic_help_box"))
        self.horizontalLayout.addWidget(self.dynamic_help_box)

        self.retranslateUi(BatchGpsImporter)
        self.tab_widget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), BatchGpsImporter.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), BatchGpsImporter.reject)
        QtCore.QMetaObject.connectSlotsByName(BatchGpsImporter)

    def retranslateUi(self, BatchGpsImporter):
        BatchGpsImporter.setWindowTitle(_translate("BatchGpsImporter", "Batch GPS Importer", None))
        self.no_scan_sub_folders_rbtn.setText(_translate("BatchGpsImporter", "No", None))
        self.label_6.setText(_translate("BatchGpsImporter", "Projection", None))
        self.route.setText(_translate("BatchGpsImporter", "Route", None))
        self.input_gpx_file_btn.setText(_translate("BatchGpsImporter", "Browse...", None))
        self.label.setText(_translate("BatchGpsImporter", "GPX folder", None))
        self.label_11.setText(_translate("BatchGpsImporter", "Geometry type", None))
        self.scan_sub_folders_rdb.setText(_translate("BatchGpsImporter", "Yes", None))
        self.label_3.setText(_translate("BatchGpsImporter", "Scan sub-folders", None))
        self.track.setText(_translate("BatchGpsImporter", "Track", None))
        self.label_2.setText(_translate("BatchGpsImporter", "GPX Format", None))
        self.waypoint.setText(_translate("BatchGpsImporter", "Waypoint", None))
        self.label_8.setText(_translate("BatchGpsImporter", "Layer name", None))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.input_output_tab), _translate("BatchGpsImporter", "Input and Output", None))
        self.label_5.setText(_translate("BatchGpsImporter", "Exclude with insufficient points", None))
        self.invalid_folder_btn.setText(_translate("BatchGpsImporter", "Browse...", None))
        self.valid_folder_btn.setText(_translate("BatchGpsImporter", "Browse...", None))
        self.label_10.setText(_translate("BatchGpsImporter", "Invalid GPX folder", None))
        self.exclude_with_few_points.setText(_translate("BatchGpsImporter", "Yes", None))
        self.no_exclude_few_points.setText(_translate("BatchGpsImporter", "No", None))
        self.no_exclude_with_errors_rbtn.setText(_translate("BatchGpsImporter", "No", None))
        self.exclude_with_errors_rbtn.setText(_translate("BatchGpsImporter", "Yes", None))
        self.label_4.setText(_translate("BatchGpsImporter", "Exclude with geometry error", None))
        self.label_7.setText(_translate("BatchGpsImporter", "Valid GPX folder", None))
        self.extent_box.setTitle(_translate("BatchGpsImporter", "Map extent (current: none)", None))
        self.extent_box.setProperty("titleBase", _translate("BatchGpsImporter", "Map extent", None))
        self.label_9.setText(_translate("BatchGpsImporter", "Exclude outside extent", None))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.validation_tab), _translate("BatchGpsImporter", "Validation", None))
        self.label_12.setText(_translate("BatchGpsImporter", "Choose layer fields", None))
        self.exclude_fields_groupbox.setTitle(_translate("BatchGpsImporter", "Check All/ Uncheck All", None))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.fields_tab), _translate("BatchGpsImporter", "Fields", None))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.log_tab), _translate("BatchGpsImporter", "Log", None))
        self.about_box.setHtml(_translate("BatchGpsImporter", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.5pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600;\">Batch GPS Importer</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">Version 0.1.1</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Batch GPS Importer is a GPX file import automation plugin that converts multiple GPX files into a single layer with multiple features based on features in each gpx file. </span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Batch GPS Importer is developed and maintained by Wondimagegn Tesfaye Beshah. </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">It is a free software under GNU General Public License.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"http://www.datumhelper.com/products/batch-gps-importer\"><span style=\" font-size:8pt; text-decoration: underline; color:#0000ff;\">Product Home</span></a><span style=\" font-size:8pt;\">, </span><a href=\"http://www.datumhelper.com/products/batch-gps-importer/documentation\"><span style=\" font-size:8pt; text-decoration: underline; color:#0000ff;\">Documentation</span></a></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Copyright © 2017 </span><a href=\"http://www.datumhelper.com/\"><span style=\" font-size:8pt; text-decoration: underline; color:#0000ff;\">Wondimagegn Tesfaye Beshah</span></a><span style=\" font-size:8pt;\">. All rights reserved.</span></p></body></html>", None))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab), _translate("BatchGpsImporter", "About", None))

from PyQt4 import QtWebKit
from qgis.gui import QgsExtentGroupBox, QgsProjectionSelectionWidget
