# Form implementation generated from reading ui file './help.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_StaticHelp(object):
    def setupUi(self, StaticHelp):
        StaticHelp.setObjectName("StaticHelp")
        StaticHelp.resize(698, 595)
        self.verticalLayout = QtWidgets.QVBoxLayout(StaticHelp)
        self.verticalLayout.setObjectName("verticalLayout")
        self.help_view = QtWebEngineWidgets.QWebEngineView(parent=StaticHelp)
        self.help_view.setUrl(QtCore.QUrl("about:blank"))
        self.help_view.setObjectName("help_view")
        self.verticalLayout.addWidget(self.help_view)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=StaticHelp)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(StaticHelp)
        self.buttonBox.accepted.connect(StaticHelp.accept) # type: ignore
        self.buttonBox.rejected.connect(StaticHelp.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(StaticHelp)

    def retranslateUi(self, StaticHelp):
        _translate = QtCore.QCoreApplication.translate
        StaticHelp.setWindowTitle(_translate("StaticHelp", "Batch GPS Importer"))
from PyQt6 import QtWebEngineWidgets
